### ISSUE TITLE
modifier mappings cannot be undone

### ISSUE THREAD

**Issue by kbilsted** [houmain/keymapper#156]
using keymapper-4.4.2-win64

I am trying to define two modes with virtual keys. Each mode should define what keys mean, in one mode everything should be as normal and in the other mode, we should have cursor movement

```

# Virtual modifiers
NORMALMODE = Virtual1
INSERTMODE = Virtual2


LOG_FILE  = c:/temp/keymapper.log
log       = $(echo "$0" > LOG_FILE)



# Passthrough window manager modifiers
MetaLeft  >> MetaLeft
MetaRight >> MetaRight


[modifier = "NORMALMODE"]
ContextActive  >> log["NORMALMODE"]  
H	            >> ArrowLeft
J	            >> ArrowDown
K	            >> ArrowUp
L	            >> ArrowRight
I 				>> !NORMALMODE INSERTMODE

[modifier = "INSERTMODE"]
ContextActive  >> log["INSERTMODE"] 
(J K) >> !INSERTMODE NORMALMODE
I >> 'I'
  
[default]
ContextActive  >> INSERTMODE
```

when i click `JK` i go into normalmode and i see the log file change and cursor movement is working

when clicking `i` i can see a change in the log file, but cursor keys are still active. Even when rebinding `i` it still does not print `i` when pressing `i`

**Comment by houmain** [comment]
Hi, thanks for reporting.
I have never though of `!Virtual` so its behavior was not defined yet. `Virtual` in the output toggles the state of the key, `!Virtual` now only releases it. Please try again with version 4.4.3 where I also fixed two more problems your configuration revealed.

**Comment by kbilsted** [comment]
thanks for the quick response. i am still facing the same issues with not being able to click `i` to escape from normal mode into insert mode and pressing i there to see "i" on the screen. i also noticed non-identical behaviour with these two configurations

```
I 				>> !NORMALMODE INSERTMODE 
```
and

```
I 				>> INSERTMODE  !NORMALMODE
```

which i would have thought were identical

**Comment by kbilsted** [comment]
wth the release at  20a91de it seems to be working now. i have not tested again the above two different ways

**Comment by houmain** [comment]
Sorry, that release was a little bit rushed before the lunch - I forgot to push. :weary:
