### ISSUE TITLE
Keys remapped to Pause outputs NumLock

### ISSUE THREAD

**Issue by rafaelferreira01** [houmain/keymapper#30]
A >> Pause  # pressing "A" outputs NumLock instead of Pause

Tested with a standard Dell Keyboard and a 60% GamaKay MK61.

**Comment by houmain** [comment]
Thanks for reporting. This should be fixed in 2.1.4.

**Comment by rafaelferreira01** [comment]
@houmain It worked! Still has a problem though. If i use the Meta key with Pause, Pause is then "changed" to NumLock.
So if i do "MetaLeft{Pause}" it will be recognized as MetaLeft{NumLock}, i think.

**Comment by rafaelferreira01** [comment]
@houmain Any news on that?

**Comment by rafaelferreira01** [comment]
Hey! Sorry for the delayed answer.
Maybe the problem is my [conf](https://github.com/houmain/keymapper/files/9135840/conf.zip) file?

With keymapper activated (with the conf file above) if i press Meta{Pause} it outputs NumLock. I can fix this by adding
Meta >> Meta on line 11 (will kinda broke another remap).
or
MetaLeft{Pause} >> MetaLeft{Pause} on line 74 (i'm using this atm).

If it matters, both my keboards need the FN key to activate the Pause button.

**Comment by houmain** [comment]
I could reproduce it with this configuration:
```
Meta{A} >> B
```
Pressing Meta+Pause triggered a Pause followed by a NumLock. 
It should be fixed in a9b62730d0641cb91ab43e476b1bf77566fa5e56. Thank you for the thorough report!

**Comment by rafaelferreira01** [comment]
Hey! The last release kinda fixed it but i'm still not able to use MetaLeft{Pause}.
If i do MetaLeft{Pause} it outputs Pause only, omiting Meta.

**Comment by houmain** [comment]
Could you please try version [2.1.6](https://github.com/houmain/keymapper/releases/tag/2.1.6)? Now it should open the windows system dialog.
